version: "3"
services:
  registration:
    image: kosticccc/eureka-server:latest
    build: eureka-server/
    ports:
      - 8761:8761
    networks:
      - app
  client:
    image: kosticccc/client-listener:latest
    build: client-listener/
    ports:
      - 8080:8080
#    depends_on:
#      - registration
    networks:
      - app
  model:
    image: kosticccc/model:latest
    build: model/
    ports:
      - 8050:8050
#    depends_on:
#      - registration
    networks:
      - app
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
networks:
  app:
    driver: bridge
